;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 4.0.2 #11690 (Linux)
;--------------------------------------------------------
; Processed by Z88DK
;--------------------------------------------------------
	
	EXTERN __divschar
	EXTERN __divschar_callee
	EXTERN __divsint
	EXTERN __divsint_callee
	EXTERN __divslong
	EXTERN __divslong_callee
	EXTERN __divslonglong
	EXTERN __divslonglong_callee
	EXTERN __divsuchar
	EXTERN __divsuchar_callee
	EXTERN __divuchar
	EXTERN __divuchar_callee
	EXTERN __divuint
	EXTERN __divuint_callee
	EXTERN __divulong
	EXTERN __divulong_callee
	EXTERN __divulonglong
	EXTERN __divulonglong_callee
	EXTERN __divuschar
	EXTERN __divuschar_callee
	EXTERN __modschar
	EXTERN __modschar_callee
	EXTERN __modsint
	EXTERN __modsint_callee
	EXTERN __modslong
	EXTERN __modslong_callee
	EXTERN __modslonglong
	EXTERN __modslonglong_callee
	EXTERN __modsuchar
	EXTERN __modsuchar_callee
	EXTERN __moduchar
	EXTERN __moduchar_callee
	EXTERN __moduint
	EXTERN __moduint_callee
	EXTERN __modulong
	EXTERN __modulong_callee
	EXTERN __modulonglong
	EXTERN __modulonglong_callee
	EXTERN __moduschar
	EXTERN __moduschar_callee
	EXTERN __mulint
	EXTERN __mulint_callee
	EXTERN __mullong
	EXTERN __mullong_callee
	EXTERN __mullonglong
	EXTERN __mullonglong_callee
	EXTERN __mulschar
	EXTERN __mulschar_callee
	EXTERN __mulsuchar
	EXTERN __mulsuchar_callee
	EXTERN __muluschar
	EXTERN __muluschar_callee
	EXTERN __rlslonglong
	EXTERN __rlslonglong_callee
	EXTERN __rlulonglong
	EXTERN __rlulonglong_callee
	EXTERN __rrslonglong
	EXTERN __rrslonglong_callee
	EXTERN __rrulonglong
	EXTERN __rrulonglong_callee
	EXTERN ___sdcc_call_hl
	EXTERN ___sdcc_call_iy
	EXTERN ___sdcc_enter_ix
	EXTERN _banked_call
	EXTERN _banked_ret
	EXTERN ___fs2schar
	EXTERN ___fs2schar_callee
	EXTERN ___fs2sint
	EXTERN ___fs2sint_callee
	EXTERN ___fs2slong
	EXTERN ___fs2slong_callee
	EXTERN ___fs2slonglong
	EXTERN ___fs2slonglong_callee
	EXTERN ___fs2uchar
	EXTERN ___fs2uchar_callee
	EXTERN ___fs2uint
	EXTERN ___fs2uint_callee
	EXTERN ___fs2ulong
	EXTERN ___fs2ulong_callee
	EXTERN ___fs2ulonglong
	EXTERN ___fs2ulonglong_callee
	EXTERN ___fsadd
	EXTERN ___fsadd_callee
	EXTERN ___fsdiv
	EXTERN ___fsdiv_callee
	EXTERN ___fseq
	EXTERN ___fseq_callee
	EXTERN ___fsgt
	EXTERN ___fsgt_callee
	EXTERN ___fslt
	EXTERN ___fslt_callee
	EXTERN ___fsmul
	EXTERN ___fsmul_callee
	EXTERN ___fsneq
	EXTERN ___fsneq_callee
	EXTERN ___fssub
	EXTERN ___fssub_callee
	EXTERN ___schar2fs
	EXTERN ___schar2fs_callee
	EXTERN ___sint2fs
	EXTERN ___sint2fs_callee
	EXTERN ___slong2fs
	EXTERN ___slong2fs_callee
	EXTERN ___slonglong2fs
	EXTERN ___slonglong2fs_callee
	EXTERN ___uchar2fs
	EXTERN ___uchar2fs_callee
	EXTERN ___uint2fs
	EXTERN ___uint2fs_callee
	EXTERN ___ulong2fs
	EXTERN ___ulong2fs_callee
	EXTERN ___ulonglong2fs
	EXTERN ___ulonglong2fs_callee
	EXTERN ____sdcc_2_copy_src_mhl_dst_deix
	EXTERN ____sdcc_2_copy_src_mhl_dst_bcix
	EXTERN ____sdcc_4_copy_src_mhl_dst_deix
	EXTERN ____sdcc_4_copy_src_mhl_dst_bcix
	EXTERN ____sdcc_4_copy_src_mhl_dst_mbc
	EXTERN ____sdcc_4_ldi_nosave_bc
	EXTERN ____sdcc_4_ldi_save_bc
	EXTERN ____sdcc_4_push_hlix
	EXTERN ____sdcc_4_push_mhl
	EXTERN ____sdcc_lib_setmem_hl
	EXTERN ____sdcc_ll_add_de_bc_hl
	EXTERN ____sdcc_ll_add_de_bc_hlix
	EXTERN ____sdcc_ll_add_de_hlix_bc
	EXTERN ____sdcc_ll_add_de_hlix_bcix
	EXTERN ____sdcc_ll_add_deix_bc_hl
	EXTERN ____sdcc_ll_add_deix_hlix
	EXTERN ____sdcc_ll_add_hlix_bc_deix
	EXTERN ____sdcc_ll_add_hlix_deix_bc
	EXTERN ____sdcc_ll_add_hlix_deix_bcix
	EXTERN ____sdcc_ll_asr_hlix_a
	EXTERN ____sdcc_ll_asr_mbc_a
	EXTERN ____sdcc_ll_copy_src_de_dst_hlix
	EXTERN ____sdcc_ll_copy_src_de_dst_hlsp
	EXTERN ____sdcc_ll_copy_src_deix_dst_hl
	EXTERN ____sdcc_ll_copy_src_deix_dst_hlix
	EXTERN ____sdcc_ll_copy_src_deixm_dst_hlsp
	EXTERN ____sdcc_ll_copy_src_desp_dst_hlsp
	EXTERN ____sdcc_ll_copy_src_hl_dst_de
	EXTERN ____sdcc_ll_copy_src_hlsp_dst_de
	EXTERN ____sdcc_ll_copy_src_hlsp_dst_deixm
	EXTERN ____sdcc_ll_lsl_hlix_a
	EXTERN ____sdcc_ll_lsl_mbc_a
	EXTERN ____sdcc_ll_lsr_hlix_a
	EXTERN ____sdcc_ll_lsr_mbc_a
	EXTERN ____sdcc_ll_push_hlix
	EXTERN ____sdcc_ll_push_mhl
	EXTERN ____sdcc_ll_sub_de_bc_hl
	EXTERN ____sdcc_ll_sub_de_bc_hlix
	EXTERN ____sdcc_ll_sub_de_hlix_bc
	EXTERN ____sdcc_ll_sub_de_hlix_bcix
	EXTERN ____sdcc_ll_sub_deix_bc_hl
	EXTERN ____sdcc_ll_sub_deix_hlix
	EXTERN ____sdcc_ll_sub_hlix_bc_deix
	EXTERN ____sdcc_ll_sub_hlix_deix_bc
	EXTERN ____sdcc_ll_sub_hlix_deix_bcix
	EXTERN ____sdcc_load_debc_deix
	EXTERN ____sdcc_load_dehl_deix
	EXTERN ____sdcc_load_debc_mhl
	EXTERN ____sdcc_load_hlde_mhl
	EXTERN ____sdcc_store_dehl_bcix
	EXTERN ____sdcc_store_debc_hlix
	EXTERN ____sdcc_store_debc_mhl
	EXTERN ____sdcc_cpu_pop_ei
	EXTERN ____sdcc_cpu_pop_ei_jp
	EXTERN ____sdcc_cpu_push_di
	EXTERN ____sdcc_outi
	EXTERN ____sdcc_outi_128
	EXTERN ____sdcc_outi_256
	EXTERN ____sdcc_ldi
	EXTERN ____sdcc_ldi_128
	EXTERN ____sdcc_ldi_256
	EXTERN ____sdcc_4_copy_srcd_hlix_dst_deix
	EXTERN ____sdcc_4_and_src_mbc_mhl_dst_deix
	EXTERN ____sdcc_4_or_src_mbc_mhl_dst_deix
	EXTERN ____sdcc_4_xor_src_mbc_mhl_dst_deix
	EXTERN ____sdcc_4_or_src_dehl_dst_bcix
	EXTERN ____sdcc_4_xor_src_dehl_dst_bcix
	EXTERN ____sdcc_4_and_src_dehl_dst_bcix
	EXTERN ____sdcc_4_xor_src_mbc_mhl_dst_debc
	EXTERN ____sdcc_4_or_src_mbc_mhl_dst_debc
	EXTERN ____sdcc_4_and_src_mbc_mhl_dst_debc
	EXTERN ____sdcc_4_cpl_src_mhl_dst_debc
	EXTERN ____sdcc_4_xor_src_debc_mhl_dst_debc
	EXTERN ____sdcc_4_or_src_debc_mhl_dst_debc
	EXTERN ____sdcc_4_and_src_debc_mhl_dst_debc
	EXTERN ____sdcc_4_and_src_debc_hlix_dst_debc
	EXTERN ____sdcc_4_or_src_debc_hlix_dst_debc
	EXTERN ____sdcc_4_xor_src_debc_hlix_dst_debc

;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
	GLOBAL _main
	GLOBAL _opts
	GLOBAL _state
;--------------------------------------------------------
; Externals used
;--------------------------------------------------------
	GLOBAL _setstate
	GLOBAL _setpalette
	GLOBAL _setimage
	GLOBAL _savestate
	GLOBAL _restorestate
	GLOBAL _remap
	GLOBAL _noattr
	GLOBAL _info
	GLOBAL _help
	GLOBAL _getopts
	GLOBAL _error
	GLOBAL _string32
	GLOBAL _getext
	GLOBAL _in_mouse_kempston_wheel_delta
	GLOBAL _in_mouse_kempston_wheel
	GLOBAL _in_mouse_kempston_callee
	GLOBAL _in_mouse_kempston
	GLOBAL _in_mouse_kempston_setpos_callee
	GLOBAL _in_mouse_kempston_setpos
	GLOBAL _in_mouse_kempston_reset
	GLOBAL _in_mouse_kempston_init
	GLOBAL _in_mouse_amx_wheel_delta
	GLOBAL _in_mouse_amx_wheel
	GLOBAL _in_mouse_amx_callee
	GLOBAL _in_mouse_amx
	GLOBAL _in_mouse_amx_setpos_callee
	GLOBAL _in_mouse_amx_setpos
	GLOBAL _in_mouse_amx_reset
	GLOBAL _in_mouse_amx_init_callee
	GLOBAL _in_mouse_amx_init
	GLOBAL _in_stick_sinclair2
	GLOBAL _in_stick_sinclair1
	GLOBAL _in_stick_kempston
	GLOBAL _in_stick_fuller
	GLOBAL _in_stick_cursor
	GLOBAL _in_stick_keyboard_fastcall
	GLOBAL _in_stick_keyboard
	GLOBAL _in_wait_nokey
	GLOBAL _in_wait_key
	GLOBAL _in_test_key
	GLOBAL _in_pause_fastcall
	GLOBAL _in_pause
	GLOBAL _in_key_scancode_fastcall
	GLOBAL _in_key_scancode
	GLOBAL _in_key_pressed_fastcall
	GLOBAL _in_key_pressed
	GLOBAL _in_inkey
	GLOBAL _esxdos_f_write_callee
	GLOBAL _esxdos_f_write
	GLOBAL _esxdos_f_read_callee
	GLOBAL _esxdos_f_read
	GLOBAL _esxdos_f_seek_callee
	GLOBAL _esxdos_f_seek
	GLOBAL _esxdos_f_fgetpos_fastcall
	GLOBAL _esxdos_f_fgetpos
	GLOBAL _esxdos_f_fstat_callee
	GLOBAL _esxdos_f_fstat
	GLOBAL _esxdos_f_sync_fastcall
	GLOBAL _esxdos_f_sync
	GLOBAL _esxdos_f_close_fastcall
	GLOBAL _esxdos_f_close
	GLOBAL _esxdos_f_open_p3_callee
	GLOBAL _esxdos_f_open_p3
	GLOBAL _esxdos_f_open_callee
	GLOBAL _esxdos_f_open
	GLOBAL _esxdos_f_unlink_fastcall
	GLOBAL _esxdos_f_unlink
	GLOBAL _esxdos_f_chdir_fastcall
	GLOBAL _esxdos_f_chdir
	GLOBAL _esxdos_f_getcwd_fastcall
	GLOBAL _esxdos_f_getcwd
	GLOBAL _esxdos_f_readdir_callee
	GLOBAL _esxdos_f_readdir
	GLOBAL _esxdos_f_opendir_p3_fastcall
	GLOBAL _esxdos_f_opendir_p3
	GLOBAL _esxdos_f_opendir_fastcall
	GLOBAL _esxdos_f_opendir
	GLOBAL _esxdos_m_getdate
	GLOBAL _esxdos_m_gethandle
	GLOBAL _esxdos_m_setdrv_fastcall
	GLOBAL _esxdos_m_setdrv
	GLOBAL _esxdos_m_getdrv
	GLOBAL _esxdos_disk_write_callee
	GLOBAL _esxdos_disk_write
	GLOBAL _esxdos_disk_read_callee
	GLOBAL _esxdos_disk_read
	GLOBAL _esxdos_disk_info_callee
	GLOBAL _esxdos_disk_info
	GLOBAL _errno_from_esxdos_fastcall
	GLOBAL _errno_from_esxdos
	GLOBAL _p3dos_pdrv_from_edrv_fastcall
	GLOBAL _p3dos_pdrv_from_edrv
	GLOBAL _p3dos_edrv_from_pdrv_fastcall
	GLOBAL _p3dos_edrv_from_pdrv
	GLOBAL _p3dos_dosname_from_catname_callee
	GLOBAL _p3dos_dosname_from_catname
	GLOBAL _p3dos_copy_pstr_to_cstr_callee
	GLOBAL _p3dos_copy_pstr_to_cstr
	GLOBAL _p3dos_copy_cstr_to_pstr_callee
	GLOBAL _p3dos_copy_cstr_to_pstr
	GLOBAL _p3dos_pstr_to_cstr_fastcall
	GLOBAL _p3dos_pstr_to_cstr
	GLOBAL _p3dos_cstr_to_pstr_fastcall
	GLOBAL _p3dos_cstr_to_pstr
	GLOBAL _esx_ide_browser_callee
	GLOBAL _esx_ide_browser
	GLOBAL _esx_ide_get_lfn_callee
	GLOBAL _esx_ide_get_lfn
	GLOBAL _esx_dos_catalog_next_fastcall
	GLOBAL _esx_dos_catalog_next
	GLOBAL _esx_dos_catalog_fastcall
	GLOBAL _esx_dos_catalog
	GLOBAL _esx_ide_bank_free_callee
	GLOBAL _esx_ide_bank_free
	GLOBAL _esx_ide_bank_reserve_callee
	GLOBAL _esx_ide_bank_reserve
	GLOBAL _esx_ide_bank_alloc_fastcall
	GLOBAL _esx_ide_bank_alloc
	GLOBAL _esx_ide_bank_avail_fastcall
	GLOBAL _esx_ide_bank_avail
	GLOBAL _esx_ide_bank_total_fastcall
	GLOBAL _esx_ide_bank_total
	GLOBAL _esx_ide_mode_set_fastcall
	GLOBAL _esx_ide_mode_set
	GLOBAL _esx_ide_mode_get_fastcall
	GLOBAL _esx_ide_mode_get
	GLOBAL _esx_dos_set_drive_fastcall
	GLOBAL _esx_dos_set_drive
	GLOBAL _esx_dos_get_drive
	GLOBAL _esx_f_unlink_fastcall
	GLOBAL _esx_f_unlink
	GLOBAL _esx_f_trunc_callee
	GLOBAL _esx_f_trunc
	GLOBAL _esx_f_stat_callee
	GLOBAL _esx_f_stat
	GLOBAL _esx_f_rename_callee
	GLOBAL _esx_f_rename
	GLOBAL _esx_f_chmod_callee
	GLOBAL _esx_f_chmod
	GLOBAL _esx_f_ftrunc_callee
	GLOBAL _esx_f_ftrunc
	GLOBAL _esx_f_write_callee
	GLOBAL _esx_f_write
	GLOBAL _esx_f_read_callee
	GLOBAL _esx_f_read
	GLOBAL _esx_f_seek_callee
	GLOBAL _esx_f_seek
	GLOBAL _esx_f_fgetpos_fastcall
	GLOBAL _esx_f_fgetpos
	GLOBAL _esx_f_fstat_callee
	GLOBAL _esx_f_fstat
	GLOBAL _esx_f_sync_fastcall
	GLOBAL _esx_f_sync
	GLOBAL _esx_f_close_fastcall
	GLOBAL _esx_f_close
	GLOBAL _esx_f_open_p3_callee
	GLOBAL _esx_f_open_p3
	GLOBAL _esx_f_open_callee
	GLOBAL _esx_f_open
	GLOBAL _esx_f_rmdir_fastcall
	GLOBAL _esx_f_rmdir
	GLOBAL _esx_f_mkdir_fastcall
	GLOBAL _esx_f_mkdir
	GLOBAL _esx_f_chdir_fastcall
	GLOBAL _esx_f_chdir
	GLOBAL _esx_f_get_canonical_path_callee
	GLOBAL _esx_f_get_canonical_path
	GLOBAL _esx_f_getcwd_drive_callee
	GLOBAL _esx_f_getcwd_drive
	GLOBAL _esx_f_getcwd_fastcall
	GLOBAL _esx_f_getcwd
	GLOBAL _esx_f_rewinddir
	GLOBAL _esx_f_seekdir_callee
	GLOBAL _esx_f_seekdir
	GLOBAL _esx_f_telldir_fastcall
	GLOBAL _esx_f_telldir
	GLOBAL _esx_slice_dirent_fastcall
	GLOBAL _esx_slice_dirent
	GLOBAL _esx_f_readdir_callee
	GLOBAL _esx_f_readdir
	GLOBAL _esx_f_closedir_fastcall
	GLOBAL _esx_f_closedir
	GLOBAL _esx_f_opendir_ex_callee
	GLOBAL _esx_f_opendir_ex
	GLOBAL _esx_f_opendir_fastcall
	GLOBAL _esx_f_opendir
	GLOBAL _esx_f_getfree
	GLOBAL _esx_m_getdate_fastcall
	GLOBAL _esx_m_getdate
	GLOBAL _esx_m_setcaps_fastcall
	GLOBAL _esx_m_setcaps
	GLOBAL _esx_m_setdrv_fastcall
	GLOBAL _esx_m_setdrv
	GLOBAL _esx_m_getdrv
	GLOBAL _esx_m_dosversion
	GLOBAL _esx_m_drvapi_fastcall
	GLOBAL _esx_m_drvapi
	GLOBAL _esx_m_geterr_callee
	GLOBAL _esx_m_geterr
	GLOBAL _esx_m_execcmd_fastcall
	GLOBAL _esx_m_execcmd
	GLOBAL _esx_m_errh_fastcall
	GLOBAL _esx_m_errh
	GLOBAL _esx_m_gethandle
	GLOBAL _esx_m_tapeout_close
	GLOBAL _esx_m_tapeout_info_callee
	GLOBAL _esx_m_tapeout_info
	GLOBAL _esx_m_tapeout_trunc_fastcall
	GLOBAL _esx_m_tapeout_trunc
	GLOBAL _esx_m_tapeout_open_fastcall
	GLOBAL _esx_m_tapeout_open
	GLOBAL _esx_m_tapein_flags_fastcall
	GLOBAL _esx_m_tapein_flags
	GLOBAL _esx_m_tapein_toggle_pause
	GLOBAL _esx_m_tapein_getpos
	GLOBAL _esx_m_tapein_setpos_fastcall
	GLOBAL _esx_m_tapein_setpos
	GLOBAL _esx_m_tapein_info_callee
	GLOBAL _esx_m_tapein_info
	GLOBAL _esx_m_tapein_close
	GLOBAL _esx_m_tapein_open_fastcall
	GLOBAL _esx_m_tapein_open
	GLOBAL _esx_disk_stream_end
	GLOBAL _esx_disk_stream_bytes_callee
	GLOBAL _esx_disk_stream_bytes
	GLOBAL _esx_disk_stream_sectors_callee
	GLOBAL _esx_disk_stream_sectors
	GLOBAL _esx_disk_stream_start_fastcall
	GLOBAL _esx_disk_stream_start
	GLOBAL _esx_disk_filemap_callee
	GLOBAL _esx_disk_filemap
	GLOBAL _extended_sna_load_fastcall
	GLOBAL _extended_sna_load
	GLOBAL _compare_dostm_callee
	GLOBAL _compare_dostm
	GLOBAL _tm_from_dostm_callee
	GLOBAL _tm_from_dostm
	GLOBAL _dostm_from_tm_callee
	GLOBAL _dostm_from_tm
	GLOBAL _tmpnam_ex_fastcall
	GLOBAL _tmpnam_ex
	GLOBAL _tmpnam_fastcall
	GLOBAL _tmpnam
	GLOBAL _vscanf_unlocked_callee
	GLOBAL _vscanf_unlocked
	GLOBAL _vprintf_unlocked_callee
	GLOBAL _vprintf_unlocked
	GLOBAL _vfscanf_unlocked_callee
	GLOBAL _vfscanf_unlocked
	GLOBAL _vfprintf_unlocked_callee
	GLOBAL _vfprintf_unlocked
	GLOBAL _ungetc_unlocked_callee
	GLOBAL _ungetc_unlocked
	GLOBAL _scanf_unlocked
	GLOBAL _rewind_unlocked_fastcall
	GLOBAL _rewind_unlocked
	GLOBAL _puts_unlocked_fastcall
	GLOBAL _puts_unlocked
	GLOBAL _putchar_unlocked_fastcall
	GLOBAL _putchar_unlocked
	GLOBAL _putc_unlocked_callee
	GLOBAL _putc_unlocked
	GLOBAL _printf_unlocked
	GLOBAL _gets_unlocked_fastcall
	GLOBAL _gets_unlocked
	GLOBAL _getline_unlocked_callee
	GLOBAL _getline_unlocked
	GLOBAL _getdelim_unlocked_callee
	GLOBAL _getdelim_unlocked
	GLOBAL _getchar_unlocked
	GLOBAL _getc_unlocked_fastcall
	GLOBAL _getc_unlocked
	GLOBAL _fwrite_unlocked_callee
	GLOBAL _fwrite_unlocked
	GLOBAL _ftell_unlocked_fastcall
	GLOBAL _ftell_unlocked
	GLOBAL _fsetpos_unlocked_callee
	GLOBAL _fsetpos_unlocked
	GLOBAL _fseek_unlocked_callee
	GLOBAL _fseek_unlocked
	GLOBAL _fscanf_unlocked
	GLOBAL _freopen_unlocked_callee
	GLOBAL _freopen_unlocked
	GLOBAL _fread_unlocked_callee
	GLOBAL _fread_unlocked
	GLOBAL _fputs_unlocked_callee
	GLOBAL _fputs_unlocked
	GLOBAL _fputc_unlocked_callee
	GLOBAL _fputc_unlocked
	GLOBAL _fprintf_unlocked
	GLOBAL _fileno_unlocked_fastcall
	GLOBAL _fileno_unlocked
	GLOBAL _fgets_unlocked_callee
	GLOBAL _fgets_unlocked
	GLOBAL _fgetpos_unlocked_callee
	GLOBAL _fgetpos_unlocked
	GLOBAL _fgetc_unlocked_fastcall
	GLOBAL _fgetc_unlocked
	GLOBAL _fflush_unlocked_fastcall
	GLOBAL _fflush_unlocked
	GLOBAL _ferror_unlocked_fastcall
	GLOBAL _ferror_unlocked
	GLOBAL _feof_unlocked_fastcall
	GLOBAL _feof_unlocked
	GLOBAL _fclose_unlocked_fastcall
	GLOBAL _fclose_unlocked
	GLOBAL _clearerr_unlocked_fastcall
	GLOBAL _clearerr_unlocked
	GLOBAL _vsscanf_callee
	GLOBAL _vsscanf
	GLOBAL _vsprintf_callee
	GLOBAL _vsprintf
	GLOBAL _vsnprintf_callee
	GLOBAL _vsnprintf
	GLOBAL _vscanf_callee
	GLOBAL _vscanf
	GLOBAL _vprintf_callee
	GLOBAL _vprintf
	GLOBAL _vfscanf_callee
	GLOBAL _vfscanf
	GLOBAL _vfprintf_callee
	GLOBAL _vfprintf
	GLOBAL _vasprintf_callee
	GLOBAL _vasprintf
	GLOBAL _ungetc_callee
	GLOBAL _ungetc
	GLOBAL _sscanf
	GLOBAL _sprintf
	GLOBAL _snprintf
	GLOBAL _scanf
	GLOBAL _rewind_fastcall
	GLOBAL _rewind
	GLOBAL _puts_fastcall
	GLOBAL _puts
	GLOBAL _putchar_fastcall
	GLOBAL _putchar
	GLOBAL _putc_callee
	GLOBAL _putc
	GLOBAL _printf
	GLOBAL _perror_fastcall
	GLOBAL _perror
	GLOBAL _open_memstream_callee
	GLOBAL _open_memstream
	GLOBAL _obstack_vprintf_callee
	GLOBAL _obstack_vprintf
	GLOBAL _obstack_printf
	GLOBAL _gets_fastcall
	GLOBAL _gets
	GLOBAL _getline_callee
	GLOBAL _getline
	GLOBAL _getdelim_callee
	GLOBAL _getdelim
	GLOBAL _getchar
	GLOBAL _getc_fastcall
	GLOBAL _getc
	GLOBAL _fwrite_callee
	GLOBAL _fwrite
	GLOBAL _funlockfile_fastcall
	GLOBAL _funlockfile
	GLOBAL _ftrylockfile_fastcall
	GLOBAL _ftrylockfile
	GLOBAL _ftell_fastcall
	GLOBAL _ftell
	GLOBAL _fsetpos_callee
	GLOBAL _fsetpos
	GLOBAL _fseek_callee
	GLOBAL _fseek
	GLOBAL _fscanf
	GLOBAL _freopen_callee
	GLOBAL _freopen
	GLOBAL _fread_callee
	GLOBAL _fread
	GLOBAL _fputs_callee
	GLOBAL _fputs
	GLOBAL _fputc_callee
	GLOBAL _fputc
	GLOBAL _fprintf
	GLOBAL _fopen_callee
	GLOBAL _fopen
	GLOBAL _fmemopen_callee
	GLOBAL _fmemopen
	GLOBAL _flockfile_fastcall
	GLOBAL _flockfile
	GLOBAL _fileno_fastcall
	GLOBAL _fileno
	GLOBAL _fgets_callee
	GLOBAL _fgets
	GLOBAL _fgetpos_callee
	GLOBAL _fgetpos
	GLOBAL _fgetc_fastcall
	GLOBAL _fgetc
	GLOBAL _fflush_fastcall
	GLOBAL _fflush
	GLOBAL _ferror_fastcall
	GLOBAL _ferror
	GLOBAL _feof_fastcall
	GLOBAL _feof
	GLOBAL _fdopen_callee
	GLOBAL _fdopen
	GLOBAL _fclose_fastcall
	GLOBAL _fclose
	GLOBAL _clearerr_fastcall
	GLOBAL _clearerr
	GLOBAL _asprintf
	GLOBAL __fmemopen__callee
	GLOBAL __fmemopen_
	GLOBAL _esx_errh
	GLOBAL _esx_stream_sectors_remaining
	GLOBAL _esx_stream_card_address
	GLOBAL _esx_stream_protocol
	GLOBAL _esx_stream_io_port
	GLOBAL _errno
	GLOBAL _stderr
	GLOBAL _stdout
	GLOBAL _stdin
	GLOBAL __MAX_FOPEN
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	SECTION bss_compiler
_state:
	DEFS 2
_opts:
	DEFS 13
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	
IF 0
	
; .area _INITIALIZED removed by z88dk
	
	
ENDIF
	
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	SECTION IGNORE
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	SECTION code_crt_init
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	SECTION IGNORE
;--------------------------------------------------------
; code
;--------------------------------------------------------
	SECTION code_compiler
;	---------------------------------
; Function main
; ---------------------------------
_main:
	push	ix
	ld	ix,0
	add	ix,sp
	ld	hl, -528
	add	hl, sp
	ld	sp, hl
	ld	hl,0
	add	hl, sp
	ex	de, hl
	ld	(_state), de
	xor	a, a
	ld	(de), a
	ld	l,(ix+6)
	ld	h,(ix+7)
	push	hl
	ld	l,(ix+4)
	ld	h,(ix+5)
	push	hl
	call	_getopts
	pop	af
	pop	af
	ld	hl, (_opts + 0)
	ld	a,0x01
	push	af
	inc	sp
	push	hl
	call	_esx_f_open_callee
	ld	a, l
	ld	b, a
	inc	a
	jr	NZ,l_main_00102
	ld	de, (_opts + 0)
	ld	a,(_errno)
	push	bc
	push	de
	ld	hl,___str_0
	push	hl
	push	af
	inc	sp
	call	_error
	pop	af
	pop	af
	inc	sp
	pop	bc
l_main_00102:
	push	bc
	call	_savestate
	call	_setstate
	pop	bc
	ld	a,(_opts + 12)
	rlca
	rlca
	rlca
	rlca
	jr	C,l_main_00104
	push	bc
	push	bc
	inc	sp
	call	_setimage
	inc	sp
	inc	sp
	call	_setpalette
	inc	sp
	jr	l_main_00105
l_main_00104:
	push	bc
	push	bc
	inc	sp
	call	_setpalette
	inc	sp
	inc	sp
	call	_setimage
	inc	sp
l_main_00105:
	ld	a,(_opts + 11)
	rrca
	and	a,0x01
	jr	NZ,l_main_00107
	call	_in_wait_key
	call	_restorestate
l_main_00107:
	ld	hl,0x0000
	ld	sp, ix
	pop	ix
	ret
	SECTION rodata_compiler
___str_0:
	DEFM "Unable to open:"
	DEFB 0x00
	SECTION IGNORE
