#include "client.h"

command commands[]={
		    { "?", cmd_help },
		    { "HELP", cmd_help },
		    { "A", cmd_ascii },
		    { "ASCII", cmd_ascii },
		    { "B", cmd_byte },
		    { "BLOCK", cmd_block },
		    { "BREAKPOINT", cmd_bkpt },
		    { "BYTE", cmd_byte },
		    { "C", cmd_cont },
		    { "CONTINUE", cmd_cont },
		    { "D", cmd_disp },
		    { "DISPLAY", cmd_disp },
		    { "E", cmd_edit },
		    { "EDITOR", cmd_edit },
		    { "Q", cmd_quit },
		    { "QUIT", cmd_quit },
		    { "G", cmd_go },
		    { "GO", cmd_go },
		    { "H", cmd_half },
		    { "HALF", cmd_half },
		    { "I", cmd_inbase },
		    { "INPUT_BASE", cmd_inbase },
		    { "L", cmd_load },
		    { "LOAD", cmd_load },
		    { "M", cmd_mnem },
		    { "MNEMONIC", cmd_mnem },
		    { "MOVE", cmd_move },
		    { "O", cmd_outbase },
		    { "OUTPUT_BASE", cmd_outbase },
		    { "P", cmd_save },
		    { "R", cmd_reg },
		    { "REGISTERS", cmd_reg },
		    { "S", cmd_sym },
		    { "SAVE", cmd_save },
		    { "SYMBOLIC", cmd_sym },
		    { "T", cmd_block },
		    { "U", cmd_move },
		    { "W", cmd_word },
		    { "WORD", cmd_word },
		    { "X", cmd_bkpt },
		    { "Y", cmd_yank },
		    { "YANK", cmd_yank },
		    { NULL, NULL }
};

		     
